version: '3.8'

services:
  endor_python:
    build:
      context: ../../../
      dockerfile: infrastructure/docker/development/app/Dockerfile
      args:
        - ENVIRONMENT=development
    container_name: endor_python_dev
    restart: unless-stopped
    env_file:
      - .env.development
    ports:
      - "8005:8000"
    volumes:
      - type: bind
        source: ${PWD}/../../../app
        target: /usr/endor_python/app
        read_only: true
    networks:
      - endor_python_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  endor_python_network:
    driver: bridge
